services:
  - type: web
    name: aethercrown98-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.main:app --workers 4 --bind 0.0.0.0:$PORT --timeout 120
    region: oregon
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: REDIS_URL
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
