apiVersion: apps/v1
kind: Deployment
metadata:
  name: aethercrown-frontend
  labels:
    app: aethercrown
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aethercrown
      component: frontend
  template:
    metadata:
      labels:
        app: aethercrown
        component: frontend
    spec:
      containers:
      - name: frontend
        image: aethercrown98/frontend:latest
        ports:
        - containerPort: 3001
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://backend-service:3000/api"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: aethercrown
    component: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: LoadBalancer
